### ISSUE TITLE
Drupal.org

### ISSUE THREAD

**Issue by danielbeeke** [strk/dolpp#3]
Why isn't this module on drupal.org?

**Comment by strk** [comment]
On Tue, Nov 22, 2011 at 05:21:50AM -0800, danielbeeke wrote:

> Why isn't this module on drupal.org?

To avoid burocracy, and because not everything in this
module is worth generalizing.

This module existed before drupal.org moved to git, btw.

I think some of the components of it would be worth
merging in the main drupal-openlayers module.

--strk; 

  ()   Free GIS & Flash consultant/developer
  /\   http://strk.keybit.net/services.html

**Comment by danielbeeke** [comment]
Ok I am trying to cluster on a map. I don't see if that is possible with this module. If so I think that should be on drupal.org or even in the openlayers module.

**Comment by strk** [comment]
On Tue, Nov 22, 2011 at 05:59:10AM -0800, danielbeeke wrote:

> Ok I am trying to cluster on a map. I don't see if that is possible
> with this module. If so I think that should be on drupal.org or even in
> the openlayers module.

I think cluster behavior itself I already put in core drupal-openlayers.
Was Drupal6 times, dunno if it still works with version 7, but I think
I've read somewhere that it was ported.

What you find in DOLPP should be dynamic style plugins making it
possible to render clustered features with a radius dependent on 
cluster population.

--strk; 

  ()   Free GIS & Flash consultant/developer
  /\   http://strk.keybit.net/services.html

**Comment by danielbeeke** [comment]
Ok thanks!

2011/11/22 strk <
reply@reply.github.com
